apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-compliance-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-compliance
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: compliance
    repoURL: https://github.com/mriensch/argo-operator-deployment
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true